"""add answer.pure_body

Revision ID: 16d071d8b4f1
Revises: 2ab98b83750d
Create Date: 2016-07-19 19:58:07.773138

"""

# revision identifiers, used by Alembic.
revision = '16d071d8b4f1'
down_revision = '2ab98b83750d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('pure_body', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'pure_body')
    ### end Alembic commands ###
