"""add user.agrees model

Revision ID: 1cf8942964bb
Revises: 16d071d8b4f1
Create Date: 2016-07-26 19:17:01.291465

"""

# revision identifiers, used by Alembic.
revision = '1cf8942964bb'
down_revision = '16d071d8b4f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('angrees', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'angrees')
    ### end Alembic commands ###
