"""add users location gender and about_me

Revision ID: 2cf83e16b3b7
Revises: 3aee409e97dd
Create Date: 2016-06-16 19:19:20.385290

"""

# revision identifiers, used by Alembic.
revision = '2cf83e16b3b7'
down_revision = '3aee409e97dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'about_me')
    ### end Alembic commands ###
