"""add avatar

Revision ID: 3aee409e97dd
Revises: 3eff9fba968e
Create Date: 2016-06-11 19:11:37.771861

"""

# revision identifiers, used by Alembic.
revision = '3aee409e97dd'
down_revision = '3eff9fba968e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
