"""add agree limit

Revision ID: 3eff9fba968e
Revises: 4338bbd691fa
Create Date: 2016-05-12 21:20:54.141563

"""

# revision identifiers, used by Alembic.
revision = '3eff9fba968e'
down_revision = '4338bbd691fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agrees',
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('answers_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answers_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agrees')
    ### end Alembic commands ###
